pub mod profile_command; 
pub mod minecraft_command;
pub mod process_command;
pub mod minecraft_auth_command;
pub mod modrinth_commands;
pub mod file_command;
pub mod config_commands;
pub mod path_commands;
pub mod cape_command;
